name: Docker Build and Push

on:
  push:
    branches: ["*"]
  pull_request:
    branches:
      - main


permissions:
  issues: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/user-management-service ./backend
          docker build -t passwordnotsafe/user-management-service:${{ github.sha }} ./backend

      - name: Push Docker Image
        run: |
          docker push passwordnotsafe/user-management-service
          docker push passwordnotsafe/user-management-service:${{ github.sha }}

      - name: Trigger fetch new sha update to k8 deployment file.
        run: |
          curl --request POST \
            --url 'https://api.github.com/repos/DevOps22-Grupp1/scamazon/actions/workflows/user-update-sha/dispatches' \
            -H "Accept: application/vnd.github+json" \
            -H 'Authorization: Bearer ${{secrets.TOKEN}}' \
            -d '{"ref:" "main"}'

      # - name: Trigger fetch new sha update to k8 deployment file.
      #   run: |
      #     curl -X POST \
      #     -H "Authorization: token ${{ secrets.TOKEN }}" \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -d '{"event_type": "custom_event_name"}' \
      #     https://api.github.com/repos/DevOps22-Grupp1/scamazon/actions/workflows/WORKFLOW_ID/dispatches


