name: Docker Build and Push

on:
  push:
    branches: ["*"]
  pull_request:
    branches:
      - main


permissions:
  issues: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t passwordnotsafe/produkt-catalog-service:${{ github.sha }} ./backend

      - name: Push Docker Image
        run: |
          docker push passwordnotsafe/produkt-catalog-service:${{ github.sha }}
      
      - name: List all ids
        run: |
          
          RESPONSE=$(curl
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/OWNER/REPO/actions/workflows
          )

          echo "$RESPONSE"

      # - name: Trigger fetch new sha update to k8 deployment file.
      #   run: |
      #     curl -X POST \
      #     -H "Authorization: token ${{ secrets.TOKEN }}" \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     -d '{"event_type": "custom_event_name"}' \
      #     https://api.github.com/repos/DevOps22-Grupp1/scamazon/actions/workflows/WORKFLOW_ID/dispatches


